name:                gameboy
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/mrehayden/gameboy#readme
license:             MPL-2.0
author:              Matthew Hayden
maintainer:          mrehayden@gmail.com
copyright:           2025 Matthew Hayden
category:            Game
extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- ConstraintKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- MagicHash
- OverloadedStrings
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- TypeFamilies
- UnliftedFFITypes

dependencies:
  - base >= 4.7 && < 5
  - array
  - lens
  - mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  exposed-modules:
  - Cpu
  - Cpu.Core
  - Data.Word.Extra
  - Rom
  source-dirs:      src

executables:
  debugger:
    dependencies:
    - gameboy
    - reflex
    - reflex-vty
    - text
    - vty
    - vty-crossplatform
    ghc-options:
    - -threaded
    - -O2
    main:           Main.hs
    source-dirs:    src-bin
